[package]
name = "wasm"
version = "0.1.0"
authors = ["Hugh Wang <hghwng@gmail.com>"]

[dependencies]
quick-xml = "0.12.1"
undrift_gps = "0.1.1"
wasm-bindgen = "0.2.11"
converter = { path = "../converter" }

[lib]
path = "lib.rs"
crate-type = ["cdylib"]
